// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0f6Kx-Ixq77JzDAKMbxwvZFBXYaoRK4M',
    appId: '1:270487164933:web:6575488d5a733fe878a46c',
    messagingSenderId: '270487164933',
    projectId: 'smap-kf',
    authDomain: 'smap-kf.firebaseapp.com',
    storageBucket: 'smap-kf.appspot.com',
    measurementId: 'G-VVXW4TWCP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU1-2C6cCaTTz2ixmoGzeuKDR_JvwdY6E',
    appId: '1:270487164933:android:d96944a8bb250d7e78a46c',
    messagingSenderId: '270487164933',
    projectId: 'smap-kf',
    storageBucket: 'smap-kf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIQRYl0VY9HIDufYniFPIWmn5sBIwAeMs',
    appId: '1:270487164933:ios:8733a42278b61f0d78a46c',
    messagingSenderId: '270487164933',
    projectId: 'smap-kf',
    storageBucket: 'smap-kf.appspot.com',
    androidClientId: '270487164933-3k3kcfrub8rtr9t87l9cnhknv2s8f5sc.apps.googleusercontent.com',
    iosClientId: '270487164933-a55sn9r5dn8r5fcga72p0k4eb7vu8p59.apps.googleusercontent.com',
    iosBundleId: 'com.kidsfun.app.kidsfun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIQRYl0VY9HIDufYniFPIWmn5sBIwAeMs',
    appId: '1:270487164933:ios:8733a42278b61f0d78a46c',
    messagingSenderId: '270487164933',
    projectId: 'smap-kf',
    storageBucket: 'smap-kf.appspot.com',
    androidClientId: '270487164933-3k3kcfrub8rtr9t87l9cnhknv2s8f5sc.apps.googleusercontent.com',
    iosClientId: '270487164933-a55sn9r5dn8r5fcga72p0k4eb7vu8p59.apps.googleusercontent.com',
    iosBundleId: 'com.kidsfun.app.kidsfun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0f6Kx-Ixq77JzDAKMbxwvZFBXYaoRK4M',
    appId: '1:270487164933:web:f75ab31c47207cab78a46c',
    messagingSenderId: '270487164933',
    projectId: 'smap-kf',
    authDomain: 'smap-kf.firebaseapp.com',
    storageBucket: 'smap-kf.appspot.com',
    measurementId: 'G-WZGTK63GME',
  );
}
